apiVersion: v1
kind: Pod
metadata:
  name: podlifecycle
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: p100-1
  serviceAccountName: octopus-tasksetcontroller
  containers:
  - name: podlifecycle
    image: yzs981130/podlifecyclelogger:version-0.0.2
    command: ["PodLifecycleLogger"]
    #args: ["--kubeconfig","/log/config"]
    restartPolicy: Always
    imagePullPolicy: Always
    volumeMounts:  
    - name: logdir
      mountPath: /log 
  volumes: 
  - name: logdir
    hostPath:  
      path: /home/amax/yezhisheng/log
